services:
  yjs_in_erlang_websocket_server1:
    image: yjs_in_erlang_websocket:${IMAGE_TAG:-latest}
    hostname: yjs_in_erlang_websocket_server1.com
    container_name: yjs_in_erlang_websocket_server1
    ports:
      - "3001:3000"
    environment:
      - YJS_IN_ERLANG_NODES="${NODES}"
      - ERLANG_NODE_NAME="yjs_in_erlang@yjs_in_erlang_websocket_server1.com"
      - COOKIE="yjs_in_erlang"
    networks:
      - app_network

  yjs_in_erlang_websocket_server2:
    image: yjs_in_erlang_websocket:${IMAGE_TAG:-latest}
    hostname: yjs_in_erlang_websocket_server2.com
    container_name: yjs_in_erlang_websocket_server2
    ports:
      - "3002:3000"
    environment:
      - YJS_IN_ERLANG_NODES="${NODES}"
      - ERLANG_NODE_NAME="yjs_in_erlang@yjs_in_erlang_websocket_server2.com"
      - COOKIE="yjs_in_erlang"
    networks:
      - app_network

  yjs_in_erlang_websocket_server3:
    image: yjs_in_erlang_websocket:${IMAGE_TAG:-latest}
    hostname: yjs_in_erlang_websocket_server3.com
    container_name: yjs_in_erlang_websocket_server3
    ports:
      - "3003:3000"
    environment:
      - YJS_IN_ERLANG_NODES="${NODES}"
      - ERLANG_NODE_NAME="yjs_in_erlang@yjs_in_erlang_websocket_server3.com"
      - COOKIE="yjs_in_erlang"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "3000:3000" # Expose the load balancer on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your NGINX config
    networks:
      - app_network
    depends_on:
      - yjs_in_erlang_websocket_server1
      - yjs_in_erlang_websocket_server2
      - yjs_in_erlang_websocket_server3

networks:
  app_network:
    driver: bridge
