services:
  yjs_in_erlang_websocket_server1:
    build: .
    container_name: yjs_in_erlang_websocket_server1
    ports:
      - "3001:3000"
    environment:
      - YJS_IN_ERLANG_NODES="yjs_in_erlang_websocket@yjs_in_erlang_websocket_server2"
    networks:
      - app_network

  yjs_in_erlang_websocket_server2:
    build: .
    container_name: yjs_in_erlang_websocket_server2
    ports:
      - "3002:3000"
    environment:
      - YJS_IN_ERLANG_NODES="yjs_in_erlang_websocket@yjs_in_erlang_websocket_server1"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "3000:3000" # Expose the load balancer on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your NGINX config
    networks:
      - app_network
    depends_on:
      - yjs_in_erlang_websocket_server1
      - yjs_in_erlang_websocket_server2

networks:
  app_network:
    driver: bridge
